name: Java CI with Gradle

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build

      - name: Get version
        run: |
          mod_version=$(grep "mod_version" gradle.properties | cut -d '=' -f2)
          echo "mod_version="$mod_version
          echo "mod_version="$mod_version >> $GITHUB_ENV

      - name: Save artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: GeometryCUI-${{ env.mod_version }}.jar
          path: build/libs/geometrycui-${{ env.mod_version}}.jar
